{% set name = "sphinx-autobuild" %}
{% set version = "2024.9.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 75929a5a92b932da8d29837406d6d973a927c456f30986a27f1f20b067897892

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - sphinx-autobuild=sphinx_autobuild.__main__:main

requirements:
  host:
    - python >=3.9
    - flit-core >=3.7
    - pip
  run:
    - starlette >=0.35
    - uvicorn >=0.25
    - websockets >=11
    - python >=3.9
    - sphinx
    - livereload
    - colorama >=0.4.6
    - watchfiles >=0.20

test:
  imports:
    - sphinx_autobuild
  commands:
    - pip check
    - sphinx-autobuild --help
    - pytest tests
  requires:
    - pip
    - pytest
    - mock
  source_files:
    - tests

about:
  home: https://github.com/executablebooks/sphinx-autobuild
  summary: Rebuild Sphinx documentation on changes, with live-reload in the browser.
  dev_url: https://github.com/sphinx-doc/sphinx-autobuild
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jrderuiter
    - xhochy
