{% set name = "sphinx-autobuild" %}
{% set version = "2024.10.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 248150f8f333e825107b6d4b86113ab28fa51750e5f9ae63b59dc339be951fb1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .
  entry_points:
    - sphinx-autobuild=sphinx_autobuild.__main__:main

requirements:
  host:
    - flit-core >=3.7
    - pip
    - python >=3.9
  run:
    - colorama >=0.4.6
    - python >=3.9
    - sphinx
    - starlette >=0.35
    - uvicorn >=0.25
    - watchfiles >=0.20
    - websockets >=11

test:
  imports:
    - sphinx_autobuild
  commands:
    - pip check
    - sphinx-autobuild --help
    - pytest -vv --color=yes --tb=long -k "not test_application"
  requires:
    - httpx
    - mock
    - pip
    - pytest >=6
  source_files:
    - tests

about:
  home: https://github.com/sphinx-doc/sphinx-autobuild
  summary: Rebuild Sphinx documentation on changes, with live-reload in the browser.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jrderuiter
    - xhochy
