{% set name = "sphinx-autobuild" %}
{% set version = "0.7.1" %}
{% set sha256 = "66388f81884666e3821edbe05dd53a0cfb68093873d17320d0610de8db28c74e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - sphinx-autobuild=sphinx_autobuild:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - watchdog >=0.7.1
    - argh >=0.24.1
    - pathtools >=0.1.2
    - pyyaml >=3.10
    - tornado >=3.2
    - port-for ==0.3.1
    - livereload >=2.3.0

test:
  imports:
    - sphinx_autobuild

  commands:
    - sphinx-autobuild --help

about:
  home: https://github.com/GaretJax/sphinx-autobuild
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Watch a Sphinx directory and rebuild the documentation when a change is detected. Also includes a livereload enabled web server.'

extra:
  recipe-maintainers:
    - jrderuiter
